version: "3.9"
services:
  node:
    depends_on:
      - mysql
      - redis
    build:
      context: .
      network: host
    ports:
      - "1111:1111"
    entrypoint: [ "./wait-for", "mysql:3306", "--", "npm", "run", "app" ]
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mysql:
    image: "mysql"
    volumes:
        - "mysql_data:/var/lib/mysql"
    restart: always
    env_file:
      .env

volumes:
   mysql_data:
